### ISSUE TITLE
cant connect

### ISSUE THREAD

**Issue by SyureD** [ETCLabs/OSCWidgets#15]
im attempting to get the widgets to work with nomad software for testing purposes and no matter what i do i cant get it to send any commands. It wont connect through tcp only seems to work with udp but still nothing. am i missing something?

**Comment by richardwilliamson** [comment]
Are you on windows or mac? Are you entering the port (3032) in osc widgets? Make sure the tx and rx port in nomad are NOT set to 3032. Also check that the version of OSC in nomad setup is 1.0 (I can’t remember if you can change it in oscwidgets)

**Comment by SyureD** [comment]
Sorry i was typing in a hurry. Im runnin it on windows. I did manage to get it working. Only on UDP on ports 8000 and 8001.   When i went the other way an set to 3032 it would connect but there would be no control. 
OsC in nomad was set to 1.0 and yes you can change it in the widgets well as of 0.6 which is what im running cant speak for previous.

**Comment by SyureD** [comment]
I managed to get it working. I was attempting to get it working on the same machine with the widgets running on one screen and the eos running on another. 

It was just for testing purposes but when I separated to two different machines it started working perfectly. 

Sorry for the delayed response. Been crazy busy at work. But thanks for the help!

**Comment by hinrichsenhans** [comment]
I'm able to get Eos and OSCWidgets talking on the same computer using TCP 1.0, port 3032, and the localhost IP address (127.0.0.1). I'll go ahead and close the issue, but do feel free to reopen or post back if you still are having trouble getting this to work on the same machine.
